feat: Infra nginx opala + jwt payload sub support (MAPCO-3998) (MAPCO-4010)
MapColonies/export-management pull request #16
Opened 2024-02-28 11:58 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                         |
| Chore            | ✖                                                                       |

2024-02-28 14:52 UTC, asafMasa requested changes
👍

2024-02-28 14:52 UTC, asafMasa commented on helm/config/nginx/nginx.conf
> +}
end of file

2024-02-28 14:52 UTC, asafMasa commented on tests/unit/taskManager/taskManager.spec.ts
> +    it('resolves and call with the received customer name', async () => {
separate methods with line

2024-02-28 14:52 UTC, asafMasa commented on tests/unit/taskManager/taskManager.spec.ts
> +    it('resolves and call with the customer name as undefined', async () => {
separate methods with line

2024-02-29 11:55 UTC, CL-SHLOMIKONCHA commented on helm/.helmignore
> +local.yaml
fixed

2024-02-29 11:55 UTC, CL-SHLOMIKONCHA commented on helm/Chart.yaml
> +    repository: oci://acrarolibotnonprod.azurecr.io/helm
fixed

2024-02-29 11:56 UTC, CL-SHLOMIKONCHA commented on helm/config/nginx/default.conf
> +    location /liveness {
fixed

2024-02-29 11:58 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +      duration: 60s # supported units (us, ms, s, m, h, d)
Roee should answer this.

2024-02-29 11:59 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  ingress:
fixed

2024-02-29 12:00 UTC, CL-SHLOMIKONCHA commented on helm/config/nginx/nginx.conf
> +}
fixed

2024-02-29 12:00 UTC, CL-SHLOMIKONCHA commented on tests/unit/taskManager/taskManager.spec.ts
> +    it('resolves and call with the received customer name', async () => {
fixed

2024-02-29 12:01 UTC, CL-SHLOMIKONCHA commented on tests/unit/taskManager/taskManager.spec.ts
> +    it('resolves and call with the customer name as undefined', async () => {
fixed

2024-02-29 12:01 UTC, CL-SHLOMIKONCHA commented on helm/templates/nginx/configmap.yaml
> +{{- end }}
fixed

2024-02-29 12:02 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    path: /
fixed

2024-05-26 11:53 UTC, merged