Implement infra nginx(MAPCO-3400)
MapColonies/export-management pull request #7
Opened 2023-09-07 11:54 UTC by almog8k

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                     |

Further  information:

2023-09-12 08:09 UTC, CL-SHLOMIKONCHA commented on helm/config/default.conf
> +
remove first empty line

2023-09-12 08:09 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  route:
add ingress section aswell

2023-09-12 08:16 UTC, almog8k commented on helm/config/default.conf
> +
done

2023-09-12 09:24 UTC, asafMasa requested changes
Good Job 👍

2023-09-12 09:24 UTC, asafMasa commented on helm/config/default.conf
> +map $msec $nanosec {
check with roee and ronen if needed as it should be in infra nginx

2023-09-12 09:24 UTC, asafMasa commented on helm/config/default.conf
> +}
end of file

2023-09-12 09:24 UTC, asafMasa commented on helm/Chart.yaml
> +dependencies:
add "common-" prefix to the name of the "export-management" and it's nginx

2023-09-12 09:24 UTC, asafMasa commented on helm/values.yaml
> +    domain: 'raster'
this should include other domains also (DEM and 3D)

2023-09-12 13:50 UTC, ronenkapelian commented on helm/config/default.conf
> +{{- $chartName := include "export-management.name" . -}}
remove if it not in use

2023-09-12 13:50 UTC, ronenkapelian commented on helm/config/default.conf
> +{{- $releaseName := .Release.Name -}}
remove if it not in use

2023-09-12 13:52 UTC, ronenkapelian commented on helm/config/default.conf
> +    fastcgi_read_timeout        300;
fastgi not relevant I think, Remove and validate correctness

2023-09-12 13:56 UTC, ronenkapelian commented on helm/config/nginx.conf
> +    log_format json escape=json
consult with Roee, on geoserver i used the default log_format of infra nginx, I think you should use it too, on future we will remove it also from pycsw the specific format

2023-09-12 14:05 UTC, ronenkapelian requested changes
few notes to resolve

2023-09-13 05:21 UTC, almog8k commented on helm/config/default.conf
> +{{- $chartName := include "export-management.name" . -}}
done

2023-09-13 05:21 UTC, almog8k commented on helm/config/default.conf
> +{{- $releaseName := .Release.Name -}}
done

2023-09-13 08:45 UTC, ronenkapelian approved these changes
Be calm! :1st_place_medal:

2023-09-13 09:51 UTC, asafMasa approved these changes

2023-09-13 11:55 UTC, merged